import {Action} from '@ngrx/store';

import {ACTIVATE_QUOTE_AUTOSAVE_BY_USER_PREF, CLEAR_QUOTE_AUTOSAVE, CLEAR_ROUTES, DEACTIVATE_QUOTE_AUTOSAVE_BY_USER_PREF, QUOTE_AUTOSAVE_ACTIVATE, QUOTE_AUTOSAVE_COMPLETE, 
    QUOTE_AUTOSAVE_DEACTIVATE, QUOTE_AUTOSAVE_INPROGRESS, QUOTE_AUTOSAVE_NEEDED, REMOVE_ACTIVE_PRODUCT_GROUP, REMOVE_ACTIVE_SERVICE_GROUP, SHOW_BLOCKER, 
    START_LOADER, STOP_LOADER, TOGGLE_QUOTE_AUTOSAVE_BY_USER_PREF, UPDATE_ACTIVE_PRODUCT_GROUPS, UPDATE_ACTIVE_SERVICE_GROUPS, UPDATE_APP_STATE, UPDATE_ROUTES} from '../appState-reducer';

export class CustomAppStateAction implements Action{
    readonly type = ACTIVATE_QUOTE_AUTOSAVE_BY_USER_PREF|| CLEAR_QUOTE_AUTOSAVE|| CLEAR_ROUTES|| DEACTIVATE_QUOTE_AUTOSAVE_BY_USER_PREF|| QUOTE_AUTOSAVE_ACTIVATE|| QUOTE_AUTOSAVE_COMPLETE|| 
    QUOTE_AUTOSAVE_DEACTIVATE|| QUOTE_AUTOSAVE_INPROGRESS|| QUOTE_AUTOSAVE_NEEDED|| REMOVE_ACTIVE_PRODUCT_GROUP|| REMOVE_ACTIVE_SERVICE_GROUP|| SHOW_BLOCKER|| 
    START_LOADER|| STOP_LOADER|| TOGGLE_QUOTE_AUTOSAVE_BY_USER_PREF|| UPDATE_ACTIVE_PRODUCT_GROUPS|| UPDATE_ACTIVE_SERVICE_GROUPS|| UPDATE_APP_STATE|| UPDATE_ROUTES;
    
    constructor(public payload:any){}
}

export type Actions = CustomAppStateAction;